package com.sahilarious.hoardr.presentation.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.sahilarious.hoardr.app.core.Status
import com.sahilarious.hoardr.domain.model.LinkModel
import com.sahilarious.hoardr.domain.repository.LinkRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class SampleViewModel @Inject constructor(
    private val linkRepository: LinkRepository
): ViewModel() {

    val linksState: StateFlow<List<LinkModel>> = linkRepository.getAllLinks()
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5000),
            initialValue = emptyList()
        )

    fun insertLink(url: String, title: String) {
        viewModelScope.launch {
            val mockLink = LinkModel(
                id = 0, // auto-generated by Room
                url = url,
                title = title,
                timestamp = System.currentTimeMillis(),
                isRead = false,
                status = Status.UNPROCESSED
            )
            linkRepository.saveLink(mockLink)
        }
    }
}